agents:
  ZeroShotAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent"
  JsonAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/toolkits/openapi"
  CSVAgent:
    documentation: "https://python.langchain.com/docs/modules/agents/toolkits/csv"
  AgentInitializer:
    documentation: "https://python.langchain.com/docs/modules/agents/agent_types/"
  VectorStoreAgent:
    documentation: ""
  VectorStoreRouterAgent:
    documentation: ""
  SQLAgent:
    documentation: ""
chains:
  LLMChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/llm_chain"
  LLMMathChain:
    documentation: "https://python.langchain.com/docs/modules/chains/additional/llm_math"
  LLMCheckerChain:
    documentation: "https://python.langchain.com/docs/modules/chains/additional/llm_checker"
  ConversationChain:
    documentation: ""
  SeriesCharacterChain:
    documentation: ""
  BaseSequentialChain:
    documentation: ""
  SalesTransformChain:
    documentation: ""
  FindPoc:
    documentation: ""
  FindTargetCompany:
    documentation: ""
  CheckDoNotCallRegistry:
    documentation: ""
  MidJourneyPromptChain:
    documentation: ""
  TimeTravelGuideChain:
    documentation: ""
  SQLDatabaseChain:
    documentation: ""
  RetrievalQA:
    documentation: "https://python.langchain.com/docs/modules/chains/popular/vector_db_qa"
  RetrievalQAWithSourcesChain:
    documentation: ""
  ConversationalRetrievalChain:
    documentation: "https://python.langchain.com/docs/modules/chains/popular/chat_vector_db"
  CombineDocsChain:
    documentation: ""
  SequentialChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/sequential_chains"
  SimpleSequentialChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/sequential_chains"
  TransformChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/transformation"

llms:
  OpenAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/openai"
  ChatOpenAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/integrations/openai"
  LlamaCpp:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp"
  CTransformers:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/ctransformers"
  Cohere:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/cohere"
  Anthropic:
    documentation: ""
  ChatAnthropic:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/integrations/anthropic"
  HuggingFaceHub:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_hub"
  VertexAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/google_vertex_ai_palm"
  ###
  # There's a bug in this component deactivating until we get it sorted: _language_models.py", line 804, in send_message
  #     is_blocked=safety_attributes.get("blocked", False),
  # AttributeError: 'list' object has no attribute 'get'
  # ChatVertexAI:
  #   documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/integrations/google_vertex_ai_palm"
  ###

prompts:
  PromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/"
  ZeroShotPrompt:
    documentation: "https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent"
textsplitters:
  CharacterTextSplitter:
    documentation: "https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/character_text_splitter"
  RecursiveCharacterTextSplitter:
    documentation: "https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter"
toolkits:
  OpenAPIToolkit:
    documentation: ""
  JsonToolkit:
    documentation: ""
  VectorStoreInfo:
    documentation: ""
  VectorStoreRouterToolkit:
    documentation: ""
  VectorStoreToolkit:
    documentation: ""
tools:
  Search:
    documentation: ""
  PAL-MATH:
    documentation: ""
  Calculator:
    documentation: ""
  Serper Search:
    documentation: ""
  Tool:
    documentation: ""
  PythonFunctionTool:
    documentation: ""
  PythonFunction:
    documentation: ""
  JsonSpec:
    documentation: ""
  News API:
    documentation: ""
  TMDB API:
    documentation: ""
  Podcast API:
    documentation: ""
  QuerySQLDataBaseTool:
    documentation: ""
  InfoSQLDatabaseTool:
    documentation: ""
  ListSQLDatabaseTool:
    documentation: ""
  BingSearchRun:
    documentation: ""
  GoogleSearchRun:
    documentation: ""
  GoogleSearchResults:
    documentation: ""
  GoogleSerperRun:
    documentation: ""
  JsonListKeysTool:
    documentation: ""
  JsonGetValueTool:
    documentation: ""
  PythonREPLTool:
    documentation: ""
  PythonAstREPLTool:
    documentation: ""
  RequestsGetTool:
    documentation: ""
  RequestsPostTool:
    documentation: ""
  RequestsPatchTool:
    documentation: ""
  RequestsPutTool:
    documentation: ""
  RequestsDeleteTool:
    documentation: ""
  WikipediaQueryRun:
    documentation: ""
  WolframAlphaQueryRun:
    documentation: ""

