agents:
  AgentInitializer:
    documentation: "https://python.langchain.com/docs/modules/agents/agent_types/"
chains:
  LLMChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/llm_chain"
  ConversationChain:
    documentation: ""
  BaseSequentialChain:
    documentation: ""
  SalesTransformChain:
    documentation: ""
  FindPoc:
    documentation: ""
  FindTargetCompany:
    documentation: ""
  CheckDoNotCallRegistry:
    documentation: ""
  SequentialChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/sequential_chains"
  SimpleSequentialChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/sequential_chains"
  TransformChain:
    documentation: "https://python.langchain.com/docs/modules/chains/foundational/transformation"

llms:
  OpenAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/openai"
  ChatOpenAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/integrations/openai"
  VertexAI:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/llms/integrations/google_vertex_ai_palm"
  ###
  # There's a bug in this component deactivating until we get it sorted: _language_models.py", line 804, in send_message
  #     is_blocked=safety_attributes.get("blocked", False),
  # AttributeError: 'list' object has no attribute 'get'
  # ChatVertexAI:
  #   documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/integrations/google_vertex_ai_palm"
  ###

prompts:
  PromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/"
  ZeroShotPrompt:
    documentation: "https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent"
tools:
  Tool:
    documentation: ""
  PythonFunctionTool:
    documentation: ""
  GetMarketingObjectives:
    documentation: ""
  # GetCustomerPocAPI:
  #   documentation: ""
  GetTopPitchableCustomer:
    documentation: ""
  # OptOutCheckupToolAPI:
  #   documentation: ""
  # ReportingAPI:
  #   documentation: ""
  FetchNextBestAction:
    documentation: ""
  GetAdsReportingData:
    documentation: ""
  PlannerAgent:
    documentation: ""
  PythonFunction:
    documentation: ""
  GoogleSerperRun:
    documentation: ""
  JsonListKeysTool:
    documentation: ""
  JsonGetValueTool:
    documentation: ""
  PythonREPLTool:
    documentation: ""
  PythonAstREPLTool:
    documentation: ""
  RequestsGetTool:
    documentation: ""
  RequestsPostTool:
    documentation: ""
  RequestsPatchTool:
    documentation: ""
  RequestsPutTool:
    documentation: ""
  RequestsDeleteTool:
    documentation: ""
  WikipediaQueryRun:
    documentation: ""
  WolframAlphaQueryRun:
    documentation: ""
